=== jason-weirather/pythologist-schemas/schemas/inputs/platforms/InForm/InForm_compound.json
{
    "$schema": "https://json-schema.org/schema#",
    "type": "object",
    "definitions":{
        "single_InForm_export":{
            "description":"A collection of exports, but may not contain all the threshold strategies.",
            "properties":{
                "export_data":{"$ref":"file:InForm.json#/definitions/export_data"},
                "annotations":{"ref":"file:inputs/annotations.json"},
                "rules":{
                    "type":"object",
                    "description":"If there are multiple InForm exports present, these rules define which features of this export to keep on merge",
                    "properties":{
                        "is_primary_mutually_exclusive_phenotyping":{
                            "type":"boolean",
                            "description":"if True, this project export is the basis for mutually exclusive phenotyping.  Other mutually exclusive phenotyping to captured from other exports should be converted to a binary phenotype in the rules defined here. At least one project must be primary."
                        },
                        "mutually_exclusive_phenotypes_to_keep_as_binary_phenotypes":{
                            "description":"This export has been phenotyped for something intended downstream to be treated as a thresholded marker.",
                            "type":"array",
                            "items":{
                                "type":"object",
                                "properties":{
                                    "mutually_exclusive_phenotype":{
                                        "description":"This needs to be a mutually exclusive phenotype defined by the annotations.",
                                        "type":"string"
                                    },
                                    "binary_phenotype_name":{
                                        "description":"This does NOT need to be a mutually exclusive phenotype defined by the panel.",
                                        "type":"string"
                                   }
                               }
                           }
                        },
                        "binary_phenotypes_to_keep":{
                            "description":"This is a list of binary phenotypes to keep from this project. If not set take merge all binary phenotypes.",
                            "type":"array",
                            "items":{
                                "type":"string",
                                "description":"Valid name of a binary phenotype."
                            }
                        }
                    },
                    "additionalProperties":false,
                    "required":["is_primary_mutually_exclusive_phenotyping"]
                }
            },
            "additionalProperties":false,
            "required":["annotations","export_data","rules"]
        }
    },
     "properties":{
        "panel":{"$ref":"file:inputs/panel.json"},
        "InForm_exports":{
            "type":"array",
            "minItems":1,
            "description":"Describe expected components of an InForm project exports. This is a list of exports from the same project for the purpose of combining thresholding strategies.",
            "items":{"$ref":"file:inputs/platforms/InForm/InForm_compound.json#/definitions/single_InForm_export"}
        },
        "meta":{"$ref":"file:inputs/platforms/InForm/InForm.json#/definitions/meta"},
        "image_attributes":{"$ref":"file:inputs/platforms/InForm/InForm.json#/definitions/image_attributes"}
    },
    "required":["InForm_exports","image_attributes","panel"]
}

=== jason-weirather/pythologist-schemas/examples/inputs/platforms/InForm/InForm_compound.json
{
    "InForm_exports":[
        {
            "export_data":{
                "component_data_tif_path":"/my/directory/structure/picture_1_component_data.tif",
                "binary_segs_maps_tif_path":"/my/directory/structure/picture_1_binary_seg_maps.tif",
                "cell_seg_data_txt_path":"/my/directory/structure/picture_1_cell_seg_data.txt",
                "score_data_txt_path":"/my/directory/structure/picture_1_score_data.txt"
            },
            "annotations":{},
            "rules":{
                "is_primary_mutually_exclusive_phenotyping":true,
                "mutually_exclusive_phenotypes_to_keep_as_binary_phenotypes":[{"CD68":"Macrophage"}],
                "binary_phenotypes_to_keep":["PD-L1"]
            }
        }
    ],
    "panel":{
        "markers":[],
        "meta":{}
    },
    "image_attributes":{
        "image_label":"picutre_1",
        "microns_per_pixel":0.496
    },
    "meta":{
        "description":"My best work yet."
    }
}
