=== jason-weirather/pythologist-schemas/pythologist_schemas/schemas/inputs/platforms/InForm/InForm.json
{
    "$schema": "https://json-schema.org/schema#",
    "type": "object",
    "description":"Define a single image analyzed in InForm.",
    "definitions":{
        "export_data":{
            "type":"object",
            "description":"These are the paths of the data elements created from InForm exports, although none are explicitly required here, what can be done downstream depends which of these are available.",
            "properties":{
                "component_data_tif_path":{
                    "type":"string",
                    "description":"A tif image with layers representative of channels measuring each stain."
                },
                "binary_segs_maps_tif_path":{
                    "type":"string",
                    "description":"A tif image with layers such as an optional processed image area mask, a nuclear and membrane mask index integer coded, and region mask."
                },
                "cell_seg_data_txt_path":{
                    "type":"string",
                    "description":"A file with the cell-phenotypes assigned per cell index, and mean intensity measures sufficient for infering any binary phenotypes."
                },
                "score_data_txt_path":{
                    "type":"string",
                    "description":"A file with one or two scores used in assigning binary phenotype thresholds."
                }
            },
            "additionalProperties":false
        },
        "meta":{
            "type":"object",
            "properties":{
                "description":{
                    "type":"string",
                    "description":"A description of the image."
                }
            },
            "additionalProperties":false
        },
        "image_attributes":{
            "type":"object",
            "properties":{
                "microns_per_pixel":{
                    "type":"number",
                    "description":"Conversion factor between micros and pixels."
                },
                "image_label":{
                    "type":"string",
                    "description":"a base name"
                }
            },
            "additionalProperties":false,
            "required":["microns_per_pixel","image_label"]
        }
    },
    "properties":{
        "panel":{"$ref":"file:inputs/panel.json"},
        "annotations":{"$ref":"file:inputs/annotations.json"},
        "export_data":{"$ref":"file:inputs/platforms/InForm/InForm.json#/definitions/export_data"},
        "meta":{"$ref":"file:inputs/platforms/InForm/InForm.json#/definitions/meta"},
        "image_attributes":{"$ref":"file:inputs/platforms/InForm/InForm.json#/definitions/image_attributes"}
    },
    "additionalProperties":false,
    "required":["panel","annotations","export_data","image_attributes"]
}

=== jason-weirather/pythologist-schemas/pythologist_schemas/json_examples/inputs/platforms/InForm/InForm.json
{
    "export_data":{
        "component_data_tif_path":"/my/directory/structure/picture_1_component_data.tif",
        "binary_segs_maps_tif_path":"/my/directory/structure/picture_1_binary_seg_maps.tif",
        "cell_seg_data_txt_path":"/my/directory/structure/picture_1_cell_seg_data.txt",
        "score_data_txt_path":"/my/directory/structure/picture_1_score_data.txt"
    },
    "panel":{
        "markers":[],
        "meta":{}
    },
    "annotations":{},
    "image_attributes":{
        "image_label":"picture_1",
        "microns_per_pixel":0.496        
    },
    "meta":{
        "description":"My best work yet."
    }
}
